<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修js基础——错误处理' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>js基础——错误处理</center></div><div class='banquan'>原文出处:本文由博客园博主皮杰克提供。<br/>
原文连接:https://www.cnblogs.com/jayking1314/p/11951147.html</div><br>
    <p>一：错误捕获</p>
<p>1.try-catch 语句（错误捕获）</p>
<div class="cnblogs_Highlighter">
<pre><code>try{

　　//这里放置可能出现问题的代码

}catch(error){

　　//错误发生时执行的代码

　　console.log(error.name)    //打印错误类型

　　console.log(error.message)  //打印错误消息

}</pre>
</div>
<p>&nbsp;说明：如果try中的代码出现任何错误，就会立即退出代码执行过程，接着执行catch块。执行过catch块之后，浏览器默认错误已经处理。</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>2.finally 字句</p>
<div class="cnblogs_Highlighter">
<pre><code>try{

}catch(error){

}finally{

}
</pre>
</div>
<p>　说明：无论try里面的语句有没有报错，catch里面的语句有没有执行到，都会执行finally语句</p>
<p>例：</p>
<div class="cnblogs_Highlighter">
<pre><code>function test(){
    try{
          return 1
    }catch(error){
         return 2 
    }finally{
         return 0  
    }
}<br />执行test函数，始终会返回0  因为最终都会执行finally块。</pre>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>3.错误类型</p>
<p>　　Error：基类型，所有错误都继承该类型</p>
<p>　　EvalError：使用eval（）函数（该函数可以执行js代码语句）异常时候抛出。通常是没有直接调用该函数会导致该错误</p>
<p>　　RangeError：数值超出相应范围触发 &nbsp; 例如：定义一个长度为 -20 &nbsp;位的数组 &nbsp; var array = new Array(-20)</p>
<p>　　ReferenceError：找不到对象时触发 &nbsp;例如：var obj = x &nbsp;在变量x未定义的情况下 抛出错误</p>
<p>　　SyntaxError：传入eval()函数的代码出现错误时抛出</p>
<p>　　TypeError：最常见，执行特定类型的操作时，变量的类型不符合要求导致 &nbsp; 例如：访问不存在的方法、变量中保存着意外的类型</p>
<p>&nbsp;</p>
<p>总结：什么时候试用try-catch语句捕获错误?</p>
<p>　　通常在大型的项目中，或者使用别人的库，源代码不能修改 &nbsp;处理那些我们无法控制的错误。</p>
<p>　　当你明确自己的代码在何时何地会出现什么错误，使用try-catch语句就不太合适了</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>二：错误抛出</p>
<p>1.throw &nbsp; &nbsp;使用throw 操作符代码会立即停止执行，除非使用try-catch捕获错误</p>
<p>基本语法 &nbsp;throw new Error('您要自定义的错误信息') &nbsp; &nbsp;throw new TypeError()...................</p>
<p>自定义错误类型</p>
<div class="cnblogs_Highlighter">
<pre><code>function MyError(message){
    this.name = MyError
    this.message = message
}

MyError.prototype = new Error()   //继承Error  因为Error是所有错误类型的基类

使用：throw new MyError('我自己定义的错误类型')　　</pre>
</div>
<p>完整案例：</p>
<div class="cnblogs_Highlighter">
<pre><code>function test(array){
	if(!(array instanceof Array)){
		throw new Error('参数不是数组')
	}
	array.sort();
	for(var i = 0;i&lt;array.length;i++){
		if(array[i]&gt;100){
			return array[i];
		}
	}
        return -1;
};

执行该函数需要传递一个数组类型的参数
首先验证参数是不是数组，如果不是数组则抛出错误</pre>
</div>
<p>总结：捕获错误的目的为了防止浏览器以默认的行为处理错误，抛出错误的目的是可以获取详细具体的错误信息</p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>